
-- Author: Brenden Boswell
-- MySQL Database Drop all tables

DROP TABLE IF EXISTS DBO.STATE;

DROP TABLE IF EXISTS DBO.ADDRESS;

DROP TABLE IF  EXISTS DBO.ADDRESS_TYPE;

DROP TABLE IF EXISTS DBO.PERSON;

DROP TABLE IF EXISTS DBO.PERSON_TYPE;

DROP TABLE IF EXISTS DBO.JOB_TITLE;

DROP TABLE IF EXISTS DBO.JOB_TITLE_TYPE;

DROP TABLE IF  EXISTS DBO.MANAGER;

DROP TABLE IF EXISTS DBO.MANAGER_TYPE;

DROP TABLE IF EXISTS DBO.DIRECT_REPORT ;

DROP TABLE IF EXISTS DBO.EMPLOYEE;

DROP TABLE IF EXISTS DBO.CUSTOMER;

DROP TABLE IF  EXISTS DBO.ACCOUNTS_PAYABLE ;

DROP TABLE IF EXISTS DBO.ACCOUNTS_RECEIVABLE;

DROP TABLE IF EXISTS DBO.EMPLOYEE_BENEFITS;

DROP TABLE IF EXISTS DBO.SURVEY;

